#CREATE DATABASE UNIMC;
USE UNIMC;

CREATE TABLE ANNOUNCE(
	ANNOUNCE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	HEADER VARCHAR(100) NOT NULL,
	META VARCHAR(200) NOT NULL,
	BODY VARCHAR(2000),
	POSTDATE TIMESTAMP DEFAULT NOW()
);