#CREATE DATABASE UNIMC;
USE UNIMC;

CREATE TABLE USER(
	UNI_EMAIL VARCHAR(320) NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	MC_NAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	UNIVERSITY VARCHAR(100) NOT NULL,
	MAJOR VARCHAR(100) NOT NULL,
	CAMPUS VARCHAR(50),
	IS_VERIFIED CHAR(1) DEFAULT 'n';
	EVERYTIME VARCHAR(100),
	REGDATE TIMESTAMP DEFAULT NOW()
);
